export const DARK_THEME = "DARK_THEME";
export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const DRAW_SIDEBAR = "DRAW_SIDEBAR";
export const DRAW_SIDEBAR_OPEN = "DRAW_SIDEBAR_OPEN";
export const DRAW_SIDEBAR_CLOSE = "DRAW_SIDEBAR_CLOSE";

export const FETCH_COURSES_START = "FETCH_COURSES_START";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAIL = "FETCH_COURSES_FAIL";